### ISSUE TITLE
Exception in console on Chrome

### ISSUE THREAD

**Issue by kudos** [mariotacke/plexify#1]
I guess IMDB's formatting changed.

```
VM875 extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property '1' of null
    at chrome.runtime.sendMessage (chrome-extension://cgckffknepmgikkhnildjodfjobncckg/src/plugins/imdb/index.js:12:55)handler @ VM875 extensions::uncaught_exception_handler:8
```

**Comment by mariotacke** [comment]
Looking into this. Can you tell me which movie you looked up on IMDb? IMDb tends to have different markup for movies that are currently playing in cinemas and or are running a media campaign.

**Comment by mariotacke** [comment]
Closing this. Let me know if you still have this problem or moved on :)
